
#Configの内容を適用したい場合は
#/reload を使用してください

#ゲームの時間です(秒)
StartTime: 10

GameTime: 900





#- Message -#
# @start = スタート時間
# @time = 時間
# @state = ゲームステータス

STARTING_COUNT: "ゲームは@start秒後に開始します"
STARTING_TITLE: "@start"

START_CHAT: "ゲームは開始されました！"
START_TITLE: "ゲーム開始！"

TELEPORT_TO_LOBBY5: "§75秒後にロビーにテレポートします..."
TELEPORT_TO_LOBBY: "§7ロビーにテレポート中..."

#- GameState -#
#- FIXED(beta-1.0): @time @start が使えるように -#

GAMESTATE_LOBBY: "ステータス: ゲーム待機中"
GAMESTATE_STARTING: "開始まで: @start 秒"
GAMESTATE_PLAYING: "残り時間: @time 秒"
GAMESTATE_ENDING: "ステータス: ゲーム終了"

#- ScoreBoard -#
# @randomint = スコアボードのみ、ランダムな数字を生成する(お遊び)
# @playername = スコアボードのみ、プレイヤーの名前を表示する
# 書き直すのがめんどくさいので、これらには32文字の制限があります

SCOREBOARD_TITLE: "§e§l攻城戦 (1.12.2)"

SCOREBOARD_LINE10: ""
SCOREBOARD_LINE9: " @state"
SCOREBOARD_LINE8: ""
SCOREBOARD_LINE7: ""
SCOREBOARD_LINE6: " @playername"
SCOREBOARD_LINE5: ""
SCOREBOARD_LINE4: ""
SCOREBOARD_LINE3: ""
SCOREBOARD_LINE2: ""
SCOREBOARD_LINE1: ""


#- Team -#
# 現在これも意味なし！ｗ
RED_TEAM: "赤チーム"
BLUE_TEAM: "青チーム"