
#Configの内容を適用したい場合は
#/reload を使用してください

#ゲームの時間です(秒)
StartTime: 10

GameTime: 900





#- Message -#
# @start = スタート時間
# @time = 時間
# @state = ゲームステータス

STARTING_COUNT: "ゲームは@start秒後に開始します"
STARTING_TITLE: "@start"

START_CHAT: "ゲームは開始されました！"
START_TITLE: "ゲーム開始！"

TELEPORT_TO_LOBBY5: "§75秒後にロビーにテレポートします..."
TELEPORT_TO_LOBBY: "§7ロビーにテレポート中..."

#- GameState -#

GAMESTATE_LOBBY: "ステータス: ゲーム待機中"
GAMESTATE_STARTING: "開始まで: @start 秒"
GAMESTATE_PLAYING: "残り時間: @time 秒"
GAMESTATE_ENDING: "ステータス: ゲーム終了"

#- Sponge -#
SCOREBOARD_IRON_TRUE: "§a破壊されていません"
SCOREBOARD_IRON_FALSE: "§c破壊されています"

SCOREBOARD_GOLD_TRUE: "§a破壊されていません"
SCOREBOARD_GOLD_FALSE: "§c破壊されています"

SCOREBOARD_DIAMOND_TRUE: "§a破壊されていません"
SCOREBOARD_DIAMOND_FALSE: "§c破壊されています"

#- ScoreBoard -#
# 上限があることに注意してください (約32文字)

# @randomint = スコアボードのみ、ランダムな数字を生成する(お遊び)
# @playername = スコアボードのみ、プレイヤーの名前を表示する
# @usedmem = スコアボードのみ、使ってるメモリー表示
# @maxmem = スコアボードのみ、最大メモリー表示
# @irons = スコアボードのみ、鉄(1)のスポンジのステータス表示
# @golds = スコアボードのみ、金(2)のスポンジのステータス表示
# @diamonds = スコアボードのみ、ダイヤ(3)のスポンジのステータス表示

SCOREBOARD_TITLE: "§e§l攻城戦 (1.12.2)"

SCOREBOARD_LINE10: ""
SCOREBOARD_LINE9: " @state"
SCOREBOARD_LINE8: " "
SCOREBOARD_LINE7: " "
SCOREBOARD_LINE6: " スポンジ(1) » @irons"
SCOREBOARD_LINE5: " §6スポンジ(2) » @golds"
SCOREBOARD_LINE4: " §bスポンジ(3) » @diamonds"
SCOREBOARD_LINE3: " "
SCOREBOARD_LINE2: " "
SCOREBOARD_LINE1: " §aメモリー > @usedmem / @maxmem MB"


#- Team -#


# DEFAULTは未実装
DEFAULT_PREFIX: "§7"
DEFAULT_CHAT_PREFIX: "[Global]"

RED_PREFIX: "§c"
RED_CHAT_PREFIX: "§c[赤チーム]"

BLUE_PREFIX: "§9"
BLUE_CHAT_PREFIX: "§9[青チーム]"

ADMIN_PREFIX: "§6[運営]"
ADMIN_CHAT_PREFIX: "§6[運営]"

#- Config Version-#
# これはsettings.ymlが書き換えられてしまうので、変えないでください
ConfigVersion: 1.2